### ISSUE TITLE
Accessing the map instance

### ISSUE THREAD

**Issue by brookmay** [thedirtyfew/dash-leaflet#78]
Hi,

There is a leaflet-control-opacity plugin in javascript (https://github.com/dayjournal/Leaflet.Control.Opacity) that I'm trying to wrap in a dash component so that it can be used in a python based dash app. But I'm facing an issue.

Basically, a map would be initialized in the dash app using dash-leaflet and within the leaflet-control-opacity's dash's component, I'm trying to get the same map instance using react-leaflet's useMap() method to do the following -

```
L.control.layers( 
   Map_BaseLayer,
   Map_AddLayer, 
).addTo(**_map_**); // here map would be the map instance/object

```
But if I do that I get the below error -
"No context provided: useLeafletContext() can only be used in a descendant of "MapContainer"

Is there a way I can pass the map object from the dash-app to the react-leaflet app?

Thanks,

**Comment by emilhe** [comment]
I think the easiest would be if you forked the repo and added the component like the other controls. Here is some inspiration,

https://github.com/thedirtyfew/dash-leaflet/blob/master/src/lib/components/MeasureControl.react.js
https://github.com/thedirtyfew/dash-leaflet/blob/master/src/lib/components/LayersControl.react.js

**Comment by brookmay** [comment]
Thanks for the suggestion. I'm still a little inclined to keep the `OpacityControl` component separate from the dash-leaflet package, so I'm still looking at other options to somehow make it work.
Do you know about react-leaflet's "useMap()" method in dash-leaflet [here](https://react-leaflet.js.org/docs/api-map/)?
It should technically work, since I'm using that method in the descendent of MapContainer, but I still get the above error I mentioned. Do you have any ideas on how I can access the map object using useMap() or something else?

**Comment by emilhe** [comment]
Dash Leaflet is based on React Leaflet version 2. You are looking at the Docs of version 3; that's probably why you are seeing the error. Sorry, I didn't notice at first.

**Comment by emilhe** [comment]
I have started looking into porting to version 3. But it will require essentially rewriting the whole libray

**Comment by brookmay** [comment]
Sorry for the intermittent replies, I don't get a lot of time to spend on my work on this plugin. 

Thanks for pointing out the version incompatibilities, I failed to notice as well. I tried the version 2 methods to access map (LeafletConsumer) but that didn't work as well. I tried the following code -

`
import { LeafletConsumer } from 'react-leaflet';
<LeafletConsumer>
  {context => console.log(context.map)}
</LeafletConsumer>
`

 where the context looks like this as per their documentation (https://react-leaflet-v2-docs.netlify.app/docs/en/context.html) -
`
type LeafletContext = {
  map?: Map,
  pane?: ?string,
  layerContainer?: ?LayerContainer,
  popupContainer?: ?Layer,
}
`

The console statement returns undefined. It seems that the context is lost in the dash conversion. 
Anyway, I just wanted to leave this note in case you find time to explore the leaflet context in react and make it available in dash-leaflet in the current version or in the next version of dash-leaflet. You have put together a great library and this is already super useful for folks who don't want to get into learning javascript from scratch.

**Comment by emilhe** [comment]
Thanks! It is possible to access the Leaflet context already. I do it in many components, e.g

https://github.com/thedirtyfew/dash-leaflet/blob/master/src/lib/components/LocateControl.react.js

**Comment by brookmay** [comment]
Yes, I saw it in your code. Although, have you tried it from outside of dash-leaflet library? Eg, in a custom dash component that is a child of dl.Map?
`
dl.Map([
      customComp(
            id="customid"
            .....
            .....
      ),
],
id="mapId", style={.....} ....)
`

When I try it, I either get undefined or "Uncaught TypeError: this._map.getSize is not a function". Let me know if it works for you, I might be missing something

**Comment by emilhe** [comment]
I haven't tried outside the library, but I would expect it to work as long as you use the `withLeaflet` HOC,

https://github.com/thedirtyfew/dash-leaflet/blob/f8823bca5f7afb0fdc99c80d5105485b72d8a8e8/src/lib/components/LocateControl.react.js#L62

**Comment by brookmay** [comment]
I tried that too. Essentially, I have tried everything that this page suggests for creating custom components - https://react-leaflet-v2-docs.netlify.app/docs/en/custom-components

**Comment by TomTom4** [comment]
Hi, 
I don't know if this would help anyone, but I encountered the exact same issue with the same need of implementing a custom control. 

I've made sure to work with *react-leaflet@2.6.3.* As @brookmay , my code would work when my app is react-based, but not if I turn it into a dash-component and pass it as a child of dl.Map. 
**However**, implementing a custom control in dash-leaflet code base , turn it into a dash-component as the other component in dash-leaflet, and passing this control as a child of dl.Map work just fine.

So because of this issue one  can not implement a dash-leaflet control as a dash-component outside of the dash-leaflet code base, 
but it is still possible to make one by adding it  directly into dash-leaflet.

**Comment by emilhe** [comment]
Hi,

While i haven’t investigated this issue further, I would like to note that I am planning to implement async loading of (some) dash-leaflet components soon. After this change has been implemented, I will be open to PRs, even if they load large external dependencies. Hence for now, I would suggest that you just implement the component in a fork of dash-leaflet and make a PR.

Cheers,
Emil

**Comment by prl900** [comment]
Thanks for the workaround @TomTom4, I think this can also be used to solve the problem in #102. 

Looking forward to seeing @emilhe async loading of components, it sounds really cool and useful. In the meantime, if anyone can give a hand with mapping the polygon drawing functionality from EditControl into a Dash button, please reach out.
